[package]
name = "chipioindustries/gameanalytics-sdk-fork"
description = "Modified GameAnalytics Roblox SDK that works in Studio"
version = "2.3.0"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["ExampleProject", "wally.exe", "aftman", "*.zip"]

[dependencies]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"